import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from 'next-themes';
import { SidebarProvider} from "@/components/ui/sidebar"
import  AppSidebar  from "@/components/app-sidebar"
import Footer from "@/components/footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Giaic Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.cdnfonts.com/css/roboto" rel="stylesheet"/>
                
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-[#23282e]`}
      >
        
        <ThemeProvider attribute="class"  enableSystem={true} >
        <SidebarProvider defaultOpen={false}>
        <div className="w-full">
        <Navbar/>
        {children}
        <Footer/>
        </div>
        <AppSidebar />
        </SidebarProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
